### ISSUE TITLE
URL service error

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/USA-Network.bundle#4]
Receiving Media Not Available errors for all Mr. Robot videos (which are the only full episodes available for the USA channel).

There is an error opening the link.theplatform.com feed which returns the Media Not Available message from line line 72 in PlayVideo (404 error)

**Comment by sander1** [comment]
Service has been updated (https://github.com/plexinc-plugins/USA-Network.bundle/compare/19fd7e2b8f8d1578c39e7271a4347866a42d06ce...2e7475b85814c8c49e03e97c2b18ddf887dff366). 0 full episodes available for Mr. Robot at the moment :'(
